{
 "title": "Generic Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details.\n",
 "tags": [
  "Go",
  "Process"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, $namespacetag)"
   },
   {
    "name": "pod",
    "query": "label_values(process_resident_memory_bytes{$namespacetag=\"$namespace\"}, $podtag)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "namespacetag", "query": "${VAR_NAMESPACETAG}" },
   { "name": "podtag", "query": "${VAR_PODTAG}" }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{$podtag}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{$namespacetag=~\"^($namespace)$\",$podtag=~\"^($pod)$\"}",
     "legendFormat": "{{$podtag}}: {{quantile}}"
    }
   ]
  }
 ]
}